version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    expose:
      - "5000"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    expose:
      - "3000"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
